version: '3.7'
services:
  mongo1:
    image: mongo:6
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30001:30001
    logging:
      driver: none

  mongo2:
    image: mongo:6
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30002:30002
    logging:
      driver: none

  mongo3:
    image: mongo:6
    container_name: mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 30003:30003
    logging:
      driver: none

  indexer:
    build: 
      context: .
      dockerfile: ./Dockerfile 
    environment:
      DATABASE_URL: mongodb://mongo1:30001/sygmaprotocol-explorer-indexer?replicaSet=my-replica-set&authSource=admin&retryWrites=true&w=majority

  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    environment:
      DATABASE_URL: mongodb://mongo1:30001/sygmaprotocol-explorer-indexer
    ports:
      - "8000:8000"