openapi: 3.0.0
info:
  title: Transfers API
  version: 1.0.0
paths:
  /api/transfers:
    get:
      summary: Get all transfers (ordered by time)
      parameters:
        - name: status
          in: query
          description: Transaction status
          schema:
            type: string
            enum: [pending, executed, failed]
        - name: page
          in: query
          description: Page number for pagination
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /api/sender/{senderAddress}/transfers:
    get:
      summary: Get all transfers initiated by specific sender
      parameters:
        - name: senderAddress
          in: path
          description: Sender address
          required: true
          schema:
            type: string
        - name: status
          in: query
          description: Transaction status
          schema:
            type: string
            enum: [pending, executed, failed]
        - name: page
          in: query
          description: Page number for pagination
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /api/resources/{resourceID}/transfers:
    get:
      summary: Get all transfers for a specific resource
      parameters:
        - name: resourceID
          in: path
          description: Resource ID
          required: true
          schema:
            type: string
        - name: status
          in: query
          description: Transaction status
          schema:
            type: string
            enum: [pending, executed, failed]
        - name: page
          in: query
          description: Page number for pagination
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          description: Number of items per page
          required: true
          schema:
            type: integer
      responses:
        200:
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /api/domains/from/{domainID}/transfers:
    get:
      summary: Get all transfers with a specific domain as source
      parameters:
        - name: domainID
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [pending, executed, failed]
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          required: true
          schema:
            type: integer
        - name: domain
          in: query
          required: true
          schema:
            type: string
            enum: [source, destination]
      responses:
        '200':
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /api/domains/to/{domainID}/transfers:
    get:
      summary: Get all transfers with a specific domain as destination
      parameters:
        - name: domainID
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [pending, executed, failed]
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          required: true
          schema:
            type: integer
        - name: domain
          in: query
          required: true
          schema:
            type: string
            enum: [source, destination]
      responses:
        '200':
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /api/domains/from/{sourceDomainID}/to/{destinationDomainID}/transfers:
    get:
      summary: Get all transfers from a specific source domain to a specific destination domain
      parameters:
        - name: sourceDomainID
          in: path
          required: true
          schema:
            type: string
        - name: destinationDomainID
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /transfers/{id}:
    get:
      summary: Retrieve a expanded specific transfer by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: ObjectId
      responses:
        '200':
          description: A single transfer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpandedTransfer'

components:
  schemas:
    ExpandedTransfer:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dcd"
        depositNonce:
          type: integer
          uniqueItems: true
          example: 1
        resource:
          $ref: '#/components/schemas/Resource'
        fromDomain:
          $ref: '#/components/schemas/Domain'
        toDomain:
          $ref: '#/components/schemas/Domain'
        sender:
          type: string
          example: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
        amount:
          type: string
          example: "1000000000000000000"
        status:
          $ref: '#/components/schemas/TransferStatus'
        fee:
          $ref: '#/components/schemas/Fee'
        deposit:
          $ref: '#/components/schemas/Deposit'
        execution:
          $ref: '#/components/schemas/Execution'
        timestamp:
          type: integer
          nullable: true
          example: 1626799380

    Transfer:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dcd"
        depositNonce:
          type: integer
          uniqueItems: true
          example: 1
        resource:
          $ref: '#/components/schemas/Resource'
        fromDomain:
          $ref: '#/components/schemas/Domain'
        toDomain:
          $ref: '#/components/schemas/Domain'
        sender:
          type: string
          example: "0x742d35Cc6634C0532925a3b844Bc454e4438f44e"
        amount:
          type: string
          example: "1000000000000000000"
        status:
          $ref: '#/components/schemas/TransferStatus'
        fee:
          $ref: '#/components/schemas/Fee'
        timestamp:
          type: integer
          nullable: true
          example: 1626799380

    TransferStatus:
      type: string
      enum:
        - pending
        - executed
        - failed

    Resource:
      type: object
      properties:
        resourceId:
          type: string
          format: ObjectId
          example: "0x0000000000000000000000000000000000000000000000000000000000000000"
        type:
          type: string
          example: "ERC20"

    Domain:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dd0"
        name:
          type: string
          example: "Ethereum"
        lastIndexedBlock:
          type: string
          example: "12984723"

    Fee:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dd2"
        amount:
          type: string
          example: "10000000000000000"
        tokenAddress:
          type: string
          example: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
        tokenSymbol:
          type: string
          example: "DAI"
        transferId:
          type: string
          format: ObjectId
          uniqueItems: true
          example: "60f7da143ce83aef2d325dcd"

    Deposit:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dd3"
        transferId:
          type: string
          format: ObjectId
          uniqueItems: true
          example: "60f7da143ce83aef2d325dcd"
        type:
          type: string
          example: "ERC20"
        txHash:
          type: string
          example: "0x9f464d3b3c85b007aef6950dbccff03e6a450a059f853802d4e7f9d4e4c8c4e2"
        blockNumber:
          type: string
          example: "12984756"
        depositData:
          type: string
          example: "0x1234567890abcdef"
        handlerResponse:
          type: string
          nullable: true
          example: "0x1234567890abcdef"

    Execution:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: "60f7da143ce83aef2d325dd4"
        transferId:
          type: string
          format: ObjectId
          uniqueItems: true
          example: "60f7da143ce83aef2d325dcd"
        type:
          type: string
          example: "ERC20"
        txHash:
          type: string
          example: "0x6b0c56d1ad5144a4bdaa7a067f8c002a7d2ad4e9f8cc00e4b4d7e6cfe1b7a8a8"
        blockNumber:
          type: string
          example: "12984799"
        handlerResponse:
          type: string
          nullable: true
          example: "0x1234567890abcdef"
        dataHash:
          type: string
          nullable: true
          example: "0x9876543210abcdef"
