name: 'Lint, Build, and Test'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn' # cache node modules
          node-version: ${{ matrix.node }}
      - run: corepack enable
      - run: yarn
      - run: yarn run lint 
      - name: Check license
        run: yarn run license-check
      - run: yarn run build
      - name: Run docker
        run: docker compose up -d
      - name: Wait
        run: sleep 50s
      - name: Run tests
        run: yarn run test