name: E2E Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run docker
        run: docker compose up -d
      - name: Wait
        run: sleep 50s
      - name: Run tests
        run: yarn run test:e2e