name: Testing indexing

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  build: 
    steps: 
      - name: Run Docker container
      - run: docker-compose -f docker-compose.e2e.yml up -d  